//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Produlator
{
    using System;
    using System.Collections.Generic;
    
    public partial class pallet
    {
        public int pallet_id { get; set; }
        public Nullable<int> products_on_pallet { get; set; }
        public Nullable<int> shelf_id { get; set; }
    
        public virtual shelf shelf { get; set; }
    }
}
